/*
 * API description for Playlist project
 *
 * This is a sample Playlist Server based on the OpenAPI 3.0 specification.  You can find out more about OpenAPI at [https://oai.github.io/Documentation](https://oai.github.io/Documentation).      Playlist server should provide following functionalities: - Upload item to server - Delete item from server - Get data from one item - Get list of all items on server - Create playlists - Modify playlists - Get a list of all existing playlists Further sources for information   - [Multipart Requests](https://swagger.io/docs/specification/describing-request-body/multipart-requests)   - [Upload And Download Multiple Files Using Web API](https://github.com/JayKrishnareddy/UploadandDownloadFiles)
 *
 * OpenAPI spec version: 1.0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Wifi.PlayListEditor.Service.Models;
using Wifi.PlayListEditor.Service.Attributes;

namespace Wifi.PlayListEditor.Service.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Route("playlistapi/v1")]
    public class PlaylistExportsApiController : ControllerBase
    {
        /// <summary>
        /// Returns available export file formats for playlists
        /// </summary>
        /// <remarks>Returns available export file formats for playlists</remarks>
        /// <response code="200">successful operation</response>
        /// <response code="500">Internal error</response>
        [HttpGet]
        [Route("playlistexports/formats")]
        [ValidateModelState]
        public virtual IActionResult PlaylistexportsFormatsGet()
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(ExportFormatList));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{\n  \"formats\" : [ {\n    \"extension\" : \".m3u\",\n    \"description\" : \"M3U Playlist format\"\n  }, {\n    \"extension\" : \".m3u\",\n    \"description\" : \"M3U Playlist format\"\n  } ]\n}";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<ExportFormatList>(exampleJson)
            : default(ExportFormatList);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Returns different file export formats for playlists
        /// </summary>
        /// <remarks>Returns different file export formats for playlists</remarks>
        /// <param name="playlistid">The playlist by id to export</param>
        /// <param name="formatExtension">The file extension of the requestsed export format</param>
        /// <response code="200">successful operation</response>
        /// <response code="404">Playlist or extension not found</response>
        [HttpGet]
        [Route("playlistexports")]
        [ValidateModelState]
        public virtual IActionResult PlaylistexportsGet([FromQuery][Required()] string playlistid, [FromQuery][Required()] string formatExtension)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(string));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "\"#EXTM3U\n#EXTINF:221,Queen - Bohemian Rhapsody\nTitel 1.mp3\n#EXTINF:473,Dire Straits - Walk Of Life\nPop\\Meine Auswahl\\Titel 2.ogg\n#EXTINF:264,冨田勲 – Boléro\nC:\\Dokumente und Einstellungen\\All Users\\Dokumente\\Eigene Musik\\Titel irgendeinenummer.flac\n#EXTINF:504,Bob Marley - Buffalo Soldier\nhttp://www.seite.invalid/musik/titel4.mp3'\n\"";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default;            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
